# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
    use_frameworks!

def sharePods
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SwiftyJSON'
    pod 'Moya/RxSwift'
end

def testPods
    pod 'Quick'
    pod 'Nimble'
    pod 'RxBlocking'
end


target 'blogupdater' do
    sharePods
end

target 'blogupdaterTests' do
    sharePods
    testPods
end
